const data = {
    products: [
        {
            _id: '1',
            name: 'Forza Horizon 5',
            category: 'Corrida',
            image: '/images/f1.jpg',
            price: 189.99,
            rating: 4.8,
            numReviews: 8,
            description: 'Sua maior aventura Horizon te espera!',
        },
        {
            _id: '2',
            name: 'GTA V',
            category: 'Ação',
            image: '/images/f2.jpg',
            price: 99.90,
            rating: 5.0,
            numReviews: 10,
            description: 'Detone tudo, seja o fodão de Los Santos!',
        },
        {
            _id: '3',
            name: 'The Witcher 3: Wild Hunt',
            category: 'Aventura',
            image: '/images/f3.jpg',
            price: 60.00,
            rating: 5.0,
            numReviews: 9,
            description: 'O lobo está de volta a caça, jogue sua moeda!',
        }, {
            _id: '4',
            name: 'The Legend of Zelda: Breath of The Wild',
            category: 'Aventura',
            image: '/images/f4.jpg',
            price: 204.99,
            rating: 5.0,
            numReviews: 10,
            description: 'Torne-se a lenda, aventure-se com o vento!',
        },
        {
            _id: '5',
            name: 'God of War',
            category: 'Aventura',
            image: '/images/f5.jpg',
            price: 79.90,
            rating: 5.0,
            numReviews: 10,
            description: 'Uma jornada nova de Kratos e Atreus, os deuses aguardam!',
        },
        {
            _id: '6',
            name: 'The Last of Us: Part II',
            category: 'Ação',
            image: '/images/f6.jpg',
            price: 200.00,
            rating: 5.0,
            numReviews: 10,
            description: 'Sobreviva a um mundo devastado e se vingue!',
        },
        {
            _id: '7',
            name: 'Hades',
            category: 'Ação',
            image: '/images/f7.jpg',
            price: 135.99,
            rating: 4.3,
            numReviews: 7,
            description: 'Fuja do reinos dos mortos e desbrave a mitologia grega!',
        },
        {
            _id: '8',
            name: 'Celeste',
            category: 'Plataforma',
            image: '/images/f8.jpg',
            price: 65.00,
            rating: 4.1,
            numReviews: 6,
            description: 'Vença a montanha, vença seus medos e transforme-se!',
        },
        {
            _id: '9',
            name: 'Halo Infinite',
            category: 'FPS',
            image: '/images/f9.jpg',
            price: 250.00,
            rating: 4.9,
            numReviews: 9,
            description: 'Embarque na nova jornada de MasterChief!',
        },
        {
            _id: '10',
            name: 'Persona 5',
            category: 'JRPG',
            image: '/images/f10.jpg',
            price: 60.00,
            rating: 4.9,
            numReviews: 10,
            description: 'Revele sua verdadeira forma, neste mundo fantástico e estiloso!',
        },
        {
            _id: '11',
            name: 'Mario Odyssey',
            category: 'Plataforma',
            image: '/images/f1.jpg',
            price: 184.99,
            rating: 5.0,
            numReviews: 9,
            description: 'Acompanhado de um chapeu mágico Mario está de volta!',
        },
        {
            _id: '12',
            name: 'Resident Evil: Village',
            category: 'FPS',
            image: '/images/f12.jpg',
            price: 205.00,
            rating: 4.8,
            numReviews: 9,
            description: 'Experimente o terror de sobrevivência como nunca antes!',
        },
        {
            _id: '13',
            name: 'Ori and the Blind Forest: Definitive Edition',
            category: 'Plataforma',
            image: '/images/f13.jpg',
            price: 55.49,
            rating: 4.2,
            numReviews: 6,
            description: 'A floresta de Nibel está morrendo, salve-a!',
        },
        {
            _id: '14',
            name: 'Sekiro: Shadows Die Twice',
            category: 'Ação',
            image: '/images/f14.jpg',
            price: 199.99,
            rating: 5.0,
            numReviews: 10,
            description: 'Trace seu próprio caminho astuto de vingança!',
        },
        {
            _id: '15',
            name: 'Civilization VI',
            category: 'Estrategia',
            image: '/images/f15.jpg',
            price: 135.00,
            rating: 4.6,
            numReviews: 6,
            description: 'Crie um império capaz de resistir ao tempo!',
        },
    ],
};
export default data;